export const products = [
  { 
    name: "Party Balloons", 
    image: "../images/balloons.jpg", 
    price: "$12.99", 
    description: "Colorful balloons for every occasion." 
  },
  { 
    name: "Tableware Set", 
    image: "../images/tableware.jpg", 
    price: "$25.99", 
    description: "Elegant tableware for party decor." 
  },
  { 
    name: "Decorative Items", 
    image: "../images/decorations.jpg", 
    price: "$18.99", 
    description: "Perfect decorative items for all party themes." 
  },
  { name: "Confetti Popper", 
    image: "../images/confetti.jpg", 
    price: "$9.99", 
    description: "Add sparkle with our confetti poppers!" },
  { name: "Birthday Banner", 
    image: "../images/banner.jpg", 
    price: "$15.99", 
    description: "Celebrate with a bright, festive banner." },
  { name: "Candle Set", 
    image: "../images/candles.jpg", 
    price: "$5.99", 
    description: "Colorful candles for every cake." },
  { name: "Party Hats", 
    image: "../images/party-hats.jpg", 
    price: "$6.99", 
    description: "Fun and festive party hats for all ages." },
  { name: "Table Cover", 
    image: "../images/table-cover.jpg", 
    price: "$11.99", 
    description: "Protect and decorate with our table covers." },
  { name: "Party Cups", 
    image: "../images/party-cups.jpg", 
    price: "$4.99", 
    description: "Disposable cups in various colors." },
  { name: "Napkins", 
    image: "../images/napkins.jpg", 
    price: "$3.99", 
    description: "Colorful napkins for every theme." },
  { name: "Party Invitations", 
    image: "../images/invitations.jpg", 
    price: "$7.99", 
    description: "Customized party invitations." },
  { name: "Party Bags", 
    image: "../images/party-bags.jpg", 
    price: "$6.49", 
    description: "Gift bags for party favors." },
  { name: "Centerpieces", 
    image: "../images/centerpieces.jpg", 
    price: "$14.99", 
    description: "Eye-catching table centerpieces." },
  { name: "Streamer Set", 
    image: "../images/streamers.jpg", 
    price: "$8.49", 
    description: "Streamers in assorted colors." },
  { name: "Photo Booth Props", 
    image: "../images/photo-props.jpg", 
    price: "$9.99", 
    description: "Fun props for your photo booth." },
  { name: "Cake Toppers", 
    image: "../images/cake-toppers.jpg", 
    price: "$4.49", 
    description: "Decorative cake toppers for any occasion." },
  { name: "Mini Pinatas", 
    image: "../images/mini-pinatas.jpg", 
    price: "$12.99", 
    description: "Small pinatas for treats." },
  { name: "Party Confetti", 
    image: "../images/confetti.jpg", 
    price: "$3.99", 
    description: "Add fun to your table decor with confetti." },
  { name: "Plastic Utensils", 
    image: "../images/utensils.jpg", 
    price: "$4.99", 
    description: "Disposable utensils for easy cleanup." },
  { name: "Face Masks", 
    image: "../images/face-masks.jpg", 
    price: "$5.99", 
    description: "Party-themed face masks for guests." },
  { name: "Popcorn Boxes", 
    image: "../images/popcorn-boxes.jpg", 
    price: "$7.99", 
    description: "Retro popcorn boxes." },
  { name: "Party Streamers", 
    image: "../images/streamers.jpg", 
    price: "$6.49", 
    description: "Colorful streamers to liven up your space." },
  { name: "Table Confetti", 
    image: "../images/table-confetti.jpg", 
    price: "$2.99", 
    description: "Sparkling table confetti for decor." },
  { name: "Costume Accessories", 
    image: "../images/costumes.jpg", 
    price: "$15.99", 
    description: "Accessories to match party themes." },
  { name: "Party Games Kit", 
    image: "../images/games-kit.jpg", 
    price: "$14.99", 
    description: "Fun games for all ages." },
  { name: "Piñata Kit", 
    image: "../images/pinata-kit.jpg", 
    price: "$20.99", 
    description: "Fillable pinata with a stick and candy." },
  { name: "LED Balloons", 
    image: "../images/led-balloons.jpg", 
    price: "$9.99", 
    description: "Glow-in-the-dark LED balloons." },
  { name: "Birthday Crowns", 
    image: "../images/birthday-crowns.jpg", 
    price: "$6.99", 
    description: "Birthday crowns for all ages." },
  { name: "Balloons Arch Kit", 
    image: "../images/arch-kit.jpg", 
    price: "$24.99", 
    description: "DIY balloon arch kit for celebrations." },
  { name: "Party Signs", 
    image: "../images/party-signs.jpg", 
    price: "$8.99", 
    description: "Directional signs to guide guests." },
  { name: "Gift Wrapping Paper", 
    image: "../images/wrapping-paper.jpg", 
    price: "$3.99", 
    description: "Beautiful wrapping paper for presents." },
  { name: "Party Sashes", 
    image: "../images/party-sashes.jpg", 
    price: "$4.99", 
    description: "Decorative sashes for special guests." }
];
